AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'reward-registration-service

  Sample SAM Template for reward-registration-service

  '
Globals:
  Function:
    Timeout: 3
Resources:
  RewadRegistrationAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: RegistrationAPI
      StageName: test
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      OpenApiVersion: 3.0.1
      BinaryMediaTypes:
      - image~1gif
      - image~1png
      - application~1json
      - text~1plain
      Tags:
        NameTag: Registration API
        ConsumerAppTag: Reward App
      Auth:
        ApiKeyRequired: true
  RewardRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reward-registration-function
      Description: Register customer to reawrad membership
      CodeUri: s3://dev-test-sam-cli/39022640572789aac1f6987110b219c5
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 512
      Timeout: 15
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: 100
      Environment:
        Variables:
          AWS_XRAY_TRACING_NAME: RegistrationService
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:GetObjectACL
          - s3:GetObjectTagging
          - s3:PutObjectTagging
          - s3:PutObject
          - s3:ReplicateTags
          Resource: arn:aws:s3:::dev-scp-reward-app/*
        - Effect: Allow
          Action:
          - SNS:Publish
          Resource: '*'
      Tags:
        NameTag: Registration Service
        ConsumerAppTag: Reward App
      Events:
        HelloWorldAPiEvent:
          Type: Api
          Properties:
            Path: /customers/rewards
            Method: post
            RestApiId:
              Ref: RewadRegistrationAPI
  RewardRegistrationApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - -apikey
      Description: CloudFormation API Key V1
      Enabled: true
      GenerateDistinctId: false
  RewardRegistrationApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: RewadRegistrationAPI
        Stage: test
      Description:
        Fn::Join:
        - ' '
        - - Ref: AWS::StackName
          - usage plan
      Quota:
        Limit: 2000
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 10
      UsagePlanName:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - -usage-plan
  RewardRegistrationApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId:
        Ref: RewardRegistrationApiKey
      KeyType: API_KEY
      UsagePlanId:
        Ref: RewardRegistrationApiUsagePlan
Outputs:
  RewardRegistrationApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${RewadRegistrationAPI}.execute-api.${AWS::Region}.amazonaws.com/test/customers/rewards
  RewardRegistrationFunction:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RewardRegistrationFunction
      - Arn
  RewardRegistrationFunctionIamRole:
    Description: Lambda Implicit IAM Role ARN
    Value:
      Fn::GetAtt:
      - RewardRegistrationFunctionRole
      - Arn
  RewardRegistrationAPIKey:
    Description: API key
    Value:
      Ref: RewardRegistrationApiKey
