AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reward-registration-service

  Sample SAM Template for reward-registration-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RewadRegistrationAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: RegistrationAPI
      StageName: test
      TracingEnabled: true
      EndpointConfiguration: REGIONAL
      OpenApiVersion: 3.0.1
      BinaryMediaTypes:
        - image~1gif
        - image~1png
        - application~1json
        - text~1plain
      Tags:
        NameTag: Registration API
        ConsumerAppTag: Reward App
        Auth:
        ApiKeyRequired: true
  RewardRegistrationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: reward-registration-function #How do I pass dynamic env value to change name
      Description: Register customer to reawrad membership
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 256
      Timeout: 15
      AutoPublishAlias: live
      Tracing: Active
      ReservedConcurrentExecutions: 100
      Environment:
        Variables:
          AWS_XRAY_TRACING_NAME: RegistrationService
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
                - s3:GetObjectTagging
                - s3:PutObjectTagging
                - s3:PutObject
                - s3:ReplicateTags
              Resource: 'arn:aws:s3:::dev-scp-reward-app/*'

      Tags: 
        NameTag: Registration Service
        ConsumerAppTag: Reward App
      Events:
        HelloWorldAPiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref RewadRegistrationAPI
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RewardRegistrationApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${RewadRegistrationAPI}.execute-api.${AWS::Region}.amazonaws.com/test/hello/"
  RewardRegistrationFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RewardRegistrationFunction.Arn
  RewardRegistrationFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RewardRegistrationFunctionRole.Arn
